### ISSUE TITLE
Can we withdraw a release once published?

### ISSUE THREAD

**Issue by Ingo60** [talios/frege-bundle#2]
Or, at least warn somehow against it's use?

As it is currently with the 3.22.324, where I noticed a bit too late that there is a bug with the handling of the precedence of (-). Fixing this was not hard, but how prevent more people from using it once it is published?

**Comment by talios** [comment]
Unfortunately Maven Central is immutable and can't/doesn't remove older versions.

I've just released/pushed 3.22.367-g2737683 to central - I must have missed seeing that secondary release.

Hopefully having the newer release available will mitigate the issue.

**Comment by Ingo60** [comment]
Thanks a lot.
I will announce it in the google groups that 324 should not be used.
